### ISSUE TITLE
auto exit after long time run

### ISSUE THREAD

**Issue by timwhitez** [Cracked5pider/Ekko#2]
Ekko.x64.exe may exit after a long time run with no error.
windows11

**Comment by Cracked5pider** [comment]
Thanks for letting me know. Can you tell me how long it took? Going to try to reproduce it.

**Comment by timwhitez** [comment]
i change "EkkoObf( 4*1000 );" to "EkkoObf( 1000 );"
and it tooks about half day to exit.
the last output was "[INFO] Wait for hEvent"

**Comment by Cracked5pider** [comment]
Aight thanks for the info. Going to take a look into this problem. And thanks for letting me know.

**Comment by timwhitez** [comment]
:）

**Comment by timwhitez** [comment]
I found that may cause by the lower time interval between RopMemEnc&RopMemDec.
